- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.buitin.command: id expense
    ignore_errors: true

    - name: say  Hello
      ansible.builtin.debug:
        msg: "hello"