- name: demo on loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}} "
    loop:
    - linux
    - shell
    - ansible
  
  - name: install package
    hosts: web
    become: tes
    tasks:
    - name: install packages
      ansible.builtin.dnf:
        name:
        state: