  - name: install packages
    hosts: web
    become: tes
    tasks:
    - name: install packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loops:
      - mysql
      - nginx
      - postfix